version: '3.7'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - api_network

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - api_network

networks:
  api_network:
