version: '3.7'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/postgres:/var/lib/postgresql/data
    networks:
      - backend_network

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend_network

networks:
  backend_network:

volumes:
    dbdata: