version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: vmg@admin.org
      PGADMIN_DEFAULT_PASSWORD: password
    restart: always
    networks:
      - backend_network

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend_network

networks:
  backend_network: